<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>blk</string>
	</array>
	<key>name</key>
	<string>BLK Syntax</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.double-slash.blk</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.blk</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.blk</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\'</string>
					<key>name</key>
					<string>constant.character.escape.blk</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.blk</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.blk</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\-?[0-9]+.?[0-9]*</string>
			<key>name</key>
			<string>constant.numeric.blk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(yes|no)</string>
			<key>name</key>
			<string>constant.other.blk</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.blk</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.blk</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([_a-zA-Z][_a-zA-Z0-9\-]*)\s*\:\s*([a-zA-Z][a-zA-Z0-9\-]*)</string>
			<key>name</key>
			<string>other.blk</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.blk</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.blk</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(include)\s+([^\s]+)</string>
			<key>name</key>
			<string>other.blk</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([_a-zA-Z][_a-zA-Z0-9\-]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.blk</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>other.blk</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.blk</string>
	<key>uuid</key>
	<string>0098dc70-2224-4180-b9f3-0b130a93dd95</string>
</dict>
</plist>
